import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    // flexDirection: 'row',
    // justifyContent: 'space-between',
    // alignItems: 'center',
    // height: 0.09,
    // backgroundColor: "white",
    // padding: 0.04,
    // elevation: 8,
    // marginTop: -7,
  },
  sideIcon: {
    // resizeMode: 'contain',
    // height: 0.06,
    // width:0.08,
  },
  logo: {
    // resizeMode: 'contain',
    // height: 0.15,
    // width: 0.15,
  },
  scrollView: {
    // flex: 1,
    backgroundColor: '#FFFFFF',
    marginBottom: 60,
  },
  header: {
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 8,
    borderBottomWidth: 1,
    elevation: 0.1,
    borderBottomColor: 'lightblue',
    right:10,
  },
  logo: {
    width: 40,
    height: 40,
    // marginRight: 0,
    marginLeft:15,
  },
  welcomeText: {
    fontSize: 15,
    fontWeight: 'semibold',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 8,
    // paddingTop:5,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: 16,
    padding:20,
  },
  brandLogo: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
  },
  emiCard: {
    backgroundColor: '#F8F9FA',
    padding: 12,
    paddingVertical:16,
    marginHorizontal: 16,
    // marginBottom: 16,
    borderRadius: 8,
  },
  emiText: {
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft:8,
  },
  emiSubText: {
    fontSize: 14,
    color: '#6C757D',
    marginVertical: 8,
  },
  startNow: {
    backgroundColor: '#000000',
    padding: 20,
    paddingHorizontal:35,
    alignSelf: 'flex-start',
    borderRadius: 4,
    alignSelf:'center',
  },
  startNowText: {
    color: '#FFFFFF',
    fontSize: 14,
  },
  grid: {
    // flexDirection: 'row',
    // alignItems:'center',
    // alignSelf:'center',
    // flexWrap: 'wrap',
    // justifyContent: 'space-between',
    padding: 5,
    marginLeft:12,
  },
  categoryCard: {
    width: 190,
    height:150,
    backgroundColor: '#6C757D19',
    borderRadius: 8,
    marginTop: 16,
    alignItems:'center',
    alignSelf: 'center',
    overflow:'hidden',
    padding: 8,
  },
  categoryText: {
    fontSize: 14,
    fontWeight: 'bold',
    margin: 10,
  },
  footerTextView: {
    flexDirection:'row',
    alignItems:'center',
    alignSelf:'center',
  },
  footerText: {
    // textAlign: 'auto',
    fontSize: 12,
    color: '#1E90F0',
    marginVertical: 16,
    padding:4,
  },
  footerTextAnd: {
    fontSize: 12,
    color: '#6C757D',
    marginVertical: 16,
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#F8F9FA',
    padding: 16,
  },
  navText: {
    fontSize: 14,
    fontWeight: 'bold',
  },
});
export default styles;
